# Generated by Django 6.0.1 on 2026-01-28 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Numéro de bordereau')),
                ('date', models.DateField(verbose_name='Date de livraison')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Espèces'), ('check', 'Chèque'), ('transfer', 'Virement'), ('mobile', 'Mobile Money'), ('credit', 'Crédit')], max_length=20, verbose_name='Mode de paiement')),
                ('delivered_by', models.CharField(blank=True, max_length=100, verbose_name='Livré par')),
                ('notes', models.TextField(blank=True, verbose_name='Observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to='clients.client', verbose_name='Client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Bordereau de livraison',
                'verbose_name_plural': 'Bordereaux de livraison',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité')),
                ('observation', models.CharField(blank=True, max_length=500, verbose_name='Observation')),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='delivery_notes.deliverynote')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'verbose_name': 'Ligne de bordereau',
                'verbose_name_plural': 'Lignes de bordereau',
            },
        ),
    ]
