# Generated by Django 6.0.1 on 2026-01-28 12:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Numéro de facture')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('finalized', 'Finalisée'), ('paid', 'Payée'), ('cancelled', 'Annulée')], default='draft', max_length=20, verbose_name='Statut')),
                ('date', models.DateField(verbose_name='Date de facture')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('total_ht', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Total HT')),
                ('total_tva', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Total TVA')),
                ('total_ttc', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Total TTC')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clients.client', verbose_name='Client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix unitaire')),
                ('tva_rate', models.DecimalField(decimal_places=2, default=Decimal('18'), max_digits=5, verbose_name='Taux TVA (%)')),
                ('total_ht', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Total HT')),
                ('total_tva', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='TVA')),
                ('total_ttc', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Total TTC')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
            },
        ),
    ]
